remotes:
  central: https://maven.central/

routing:
  /:
    '*':
    - todo
    'org.apache:*':
    - central

misc:
  use_regex: false

server:
  port: 80
  ssl:
    public_key: x.test
    private_key: y.test
  error_page: 404.htm