remotes:
  central: https://maven.central/

routing:
  /private:
    '*':
    - todo
    'org.apache:*':
    - central
  /public:
    '*':
    - todo
  /public/apache:
    '*':
    - central 

misc:
  use_regex: false

repository:
  location: repo

server:
  port: 80
  ssl:
    public_key: x.test
    private_key: y.test
  error_page: 404.htm
